Repository patchlevel/event-sourcing-bundle, pull requests merged in 2022-01, with the labels that each got.

#41 fix typo in projection documentation
  docs/projection.md
Labels: documentation

#30 add profiler
  Makefile
  composer.json
  composer.lock
  phpstan-baseline.neon
  src/DataCollector/EventCollector.php
  src/DataCollector/EventListener.php
  src/DependencyInjection/Compiler/ProcessorPass.php
  src/DependencyInjection/PatchlevelEventSourcingExtension.php
  src/PatchlevelEventSourcingBundle.php
  src/Resources/views/Collector/icon.svg
  src/Resources/views/Collector/template.html.twig
  tests/Unit/PatchlevelEventSourcingBundleTest.php
Labels: enhancement

#34 add attributes support for aggregates
  README.md
  composer.json
  composer.lock
  src/Attribute/Aggregate.php
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/PatchlevelEventSourcingExtension.php
  src/Loader/AggregateAttributesLoader.php
  tests/Fixtures/AttributedAggregates/ProfileWithAttribute.php
  tests/Fixtures/AttributedAggregates/SnapshotableProfileWithAttribute.php
  tests/Fixtures/AttributedAggregatesSameName/ProfileWithAttribute.php
  tests/Fixtures/AttributedAggregatesSameName/SnapshotableProfileWithAttribute.php
  tests/Unit/AggregateAttributeLoaderTest.php
  tests/Unit/PatchlevelEventSourcingBundleTest.php
Labels: enhancement

#42 allow to install patch versions for symfony 5
  composer.json
  composer.lock
Labels: bug

#40 add batch snapshotstore support
  composer.json
  composer.lock
  docs/snapshots.md
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/PatchlevelEventSourcingExtension.php
  tests/Unit/PatchlevelEventSourcingBundleTest.php
Labels: enhancement

#46 add aggregate documentation
  README.md
  docs/aggregate.md
  docs/installation.md
  docs/snapshots.md
Labels: documentation

#63 fix data collector for symfony 4
  src/DataCollector/EventCollector.php
  src/DependencyInjection/PatchlevelEventSourcingExtension.php
  tests/Fixtures/ProfileCreated.php
  tests/Unit/AggregateAttributeLoaderTest.php
  tests/Unit/DataCollector/EventCollectorTest.php
  tests/Unit/Loader/AggregateAttributeLoaderTest.php
Labels: bug

#66 Try to "widen" the deps, since we want to support multiple symfony major versions
  .github/dependabot.yml
Labels: dependencies
