Repository patchlevel/event-sourcing-bundle, pull requests merged in 2024-01, with the labels that each got.

#157 add auto recovery and teardown
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/PatchlevelEventSourcingExtension.php
  src/Listener/ProjectionistAutoRecoveryListener.php
  src/Listener/ProjectionistAutoTeardownListener.php
  tests/Unit/PatchlevelEventSourcingBundleTest.php
Labels: enhancement

#160 use the right logger service to add log messages into "event_sourcing" channel
  src/DependencyInjection/PatchlevelEventSourcingExtension.php
Labels: bug

#161 execute teardown listener by terminate & throw error in boot listener
  src/Listener/ProjectionistAutoBootListener.php
  src/Listener/ProjectionistAutoTeardownListener.php
Labels: enhancement

#162 Fix some more issues in getting started docs
  docs/pages/getting_started.md
Labels: documentation

#163 Use new event bus & remove symfony messenger support
  composer.json
  composer.lock
  docs/pages/getting_started.md
  docs/pages/processor.md
  docs/pages/store.md
  src/Attribute/AsProcessor.php
  src/DataCollector/MessageListener.php
  src/DependencyInjection/Compiler/ProcessorPass.php
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/PatchlevelEventSourcingExtension.php
  src/PatchlevelEventSourcingBundle.php
  tests/Fixtures/CreatedSubscriber.php
  tests/Fixtures/Processor1.php
  tests/Fixtures/Processor2.php
  tests/Unit/PatchlevelEventSourcingBundleTest.php
Labels: enhancement, BC-Break

#164 add symfony messenger support & update docs
  docs/pages/event_bus.md
  docs/pages/processor.md
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/PatchlevelEventSourcingExtension.php
  src/EventBus/SymfonyEventBus.php
  tests/Unit/EventBus/SymfonyEventBusTest.php
  tests/Unit/PatchlevelEventSourcingBundleTest.php
Labels: enhancement

#167 upgrade event sourcing to 3.0.0-rc4
  composer.json
  composer.lock
Labels: bug

#169 inject projector metadata factory
  src/DependencyInjection/PatchlevelEventSourcingExtension.php
Labels: enhancement
